version: "3"

services:
  postgre-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=MessageExpert.Services.Api.ProdDb
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  core-api:
    ports:
      - '82:80'
    volumes:
      - /environments/prod/appsettings.json:/app/appsettings.json
    restart: always

volumes:
  pgdata:
    driver: local