version: "3"

services:
  postgre-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=MessageExpert.Services.ApiDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  core-api:
    ports:
      - '80:80'
    volumes:
      - c:/environments/appsettings.json:/app/appsettings.json
    restart: always

volumes:
  pgdata:
    driver: local