version: "2"

services:
  postgre-db:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=MessageExpert.Services.Api.TestDb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  core-api:
    ports:
      - '81:80'
    volumes:
      - /environments/test/appsettings.json:/app/appsettings.json

volumes:
  pgdata:
    driver: local